
debug: true

unlock_quests:
  9:
    type: statistic
    statistic: walk_one_cm
    amount: 10000 # 1000m
  10:
    type: statistic
    statistic: jump
    amount: 1000
  11:
    type: statistic
    statistic: mob_kills
    amount: 100
  12:
    type: statistic
    statistic: mob_kills
    amount: 100
  13:
    type: statistic
    statistic: damage_taken
    amount: 30000
  14:
    type: statistic
    statistic: damage_blocked_by_shield
    amount: 1000
  15:
    type: statistic
    statistic: item_enchanted
    amount: 42
  16:
    type: statistic
    statistic: damage_resisted
    amount: 10000
  17:
    type: statistic
    statistic: fish_caught
    amount: 100
  18:
    type: statistic
    statistic: sleep_in_bed
    amount: 30
  19:
    type: break_block
    block: deepslate_diamond_ore
    amount: 128
  20:
    type: break_block
    block: amethyst_block
    amount: 256
  21:
    type: break_block
    block: ancient_debris
    amount: 100